export const menuItems = {
    "main-courses": [
        // Gluten-Free Options
        {
            "id": 1,
            "name": "Grilled Salmon with Herbs",
            "description": "Fresh Atlantic salmon with herbs and lemon butter sauce",
            "price": 28.99,
            "image": "https://images.unsplash.com/photo-1467003909585-2f8a72700288",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "25 mins",
            "rating": 4.8,
            "isNew": true,
            "dietary": ["gluten-free"]
        },
        {
            "id": 2,
            "name": "Herb-Crusted Chicken",
            "description": "Free-range chicken breast with fresh herbs and roasted vegetables",
            "price": 24.99,
            "image": "https://images.unsplash.com/photo-1532550907401-a500c9a57435",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "30 mins",
            "rating": 4.7,
            "isNew": false,
            "dietary": ["gluten-free"]
        },
        {
            "id": 3,
            "name": "Grilled Ribeye Steak",
            "description": "Premium aged ribeye with garlic butter and seasonal vegetables",
            "price": 36.99,
            "image": "https://images.unsplash.com/photo-1544025162-d76694265947",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "25 mins",
            "rating": 4.9,
            "isNew": false,
            "dietary": ["gluten-free"]
        },
        {
            "id": 4,
            "name": "Pan-Seared Sea Bass",
            "description": "Fresh sea bass with citrus sauce and quinoa",
            "price": 32.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "28 mins",
            "rating": 4.8,
            "isNew": false,
            "dietary": ["gluten-free"]
        },
        {
            "id": 5,
            "name": "Grilled Pork Chop",
            "description": "Heritage pork with apple chutney and roasted potatoes",
            "price": 27.99,
            "image": "https://images.unsplash.com/photo-1544025162-d76694265947",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "30 mins",
            "rating": 4.6,
            "isNew": true,
            "dietary": ["gluten-free"]
        },
        {
            "id": 6,
            "name": "Roasted Duck Breast",
            "description": "Duck breast with cherry sauce and wild rice",
            "price": 34.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "35 mins",
            "rating": 4.8,
            "isNew": false,
            "dietary": ["gluten-free"]
        },
        {
            "id": 7,
            "name": "Grilled Lamb Chops",
            "description": "New Zealand lamb with mint sauce and roasted vegetables",
            "price": 38.99,
            "image": "https://images.unsplash.com/photo-1544025162-d76694265947",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "30 mins",
            "rating": 4.9,
            "isNew": false,
            "dietary": ["gluten-free"]
        },
        {
            "id": 8,
            "name": "Seared Tuna Steak",
            "description": "Sesame-crusted tuna with Asian slaw",
            "price": 29.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "20 mins",
            "rating": 4.7,
            "isNew": true,
            "dietary": ["gluten-free"]
        },
        {
            "id": 9,
            "name": "Roasted Chicken",
            "description": "Whole roasted chicken with herbs and root vegetables",
            "price": 26.99,
            "image": "https://images.unsplash.com/photo-1532550907401-a500c9a57435",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "45 mins",
            "rating": 4.6,
            "isNew": false,
            "dietary": ["gluten-free"]
        },
        {
            "id": 10,
            "name": "Grilled Mahi Mahi",
            "description": "Fresh Mahi Mahi with tropical salsa",
            "price": 27.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "25 mins",
            "rating": 4.7,
            "isNew": true,
            "dietary": ["gluten-free"]
        },

        // Vegetarian Options
        {
            "id": 11,
            "name": "Mushroom Risotto",
            "description": "Creamy Arborio rice with wild mushrooms and parmesan",
            "price": 22.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "30 mins",
            "rating": 4.7,
            "isNew": false,
            "dietary": ["vegetarian"]
        },
        {
            "id": 12,
            "name": "Eggplant Parmesan",
            "description": "Breaded eggplant with marinara sauce and melted mozzarella",
            "price": 21.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "35 mins",
            "rating": 4.6,
            "isNew": false,
            "dietary": ["vegetarian"]
        },
        {
            "id": 13,
            "name": "Spinach and Ricotta Ravioli",
            "description": "Handmade pasta filled with spinach and ricotta cheese",
            "price": 23.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "25 mins",
            "rating": 4.8,
            "isNew": true,
            "dietary": ["vegetarian"]
        },
        {
            "id": 14,
            "name": "Vegetable Lasagna",
            "description": "Layered pasta with seasonal vegetables and bechamel sauce",
            "price": 20.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "40 mins",
            "rating": 4.5,
            "isNew": false,
            "dietary": ["vegetarian"]
        },
        {
            "id": 15,
            "name": "Stuffed Bell Peppers",
            "description": "Bell peppers filled with quinoa, vegetables, and cheese",
            "price": 19.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "35 mins",
            "rating": 4.6,
            "isNew": true,
            "dietary": ["vegetarian"]
        },
        {
            "id": 16,
            "name": "Portobello Mushroom Steak",
            "description": "Grilled portobello with balsamic glaze and vegetables",
            "price": 21.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "25 mins",
            "rating": 4.7,
            "isNew": false,
            "dietary": ["vegetarian"]
        },
        {
            "id": 17,
            "name": "Three Cheese Gnocchi",
            "description": "Potato gnocchi in a creamy three-cheese sauce",
            "price": 22.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "30 mins",
            "rating": 4.8,
            "isNew": true,
            "dietary": ["vegetarian"]
        },
        {
            "id": 18,
            "name": "Mediterranean Quiche",
            "description": "Flaky pastry filled with vegetables and feta cheese",
            "price": 20.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "40 mins",
            "rating": 4.5,
            "isNew": false,
            "dietary": ["vegetarian"]
        },
        {
            "id": 19,
            "name": "Vegetable Stir Fry",
            "description": "Asian-style vegetables with tofu in ginger sauce",
            "price": 19.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "20 mins",
            "rating": 4.6,
            "isNew": false,
            "dietary": ["vegetarian"]
        },
        {
            "id": 20,
            "name": "Pumpkin Ravioli",
            "description": "Handmade pasta filled with pumpkin and sage butter sauce",
            "price": 23.99,
            "image": "https://images.unsplash.com/photo-1476124369491-e7addf5db371",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "35 mins",
            "rating": 4.7,
            "isNew": true,
            "dietary": ["vegetarian"]
        },

        // Vegan Options
        {
            "id": 21,
            "name": "Buddha Bowl",
            "description": "Quinoa, roasted vegetables, avocado, and tahini dressing",
            "price": 19.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "20 mins",
            "rating": 4.7,
            "isNew": true,
            "dietary": ["vegan"]
        },
        {
            "id": 22,
            "name": "Cauliflower Steak",
            "description": "Roasted cauliflower with chimichurri sauce",
            "price": 18.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "25 mins",
            "rating": 4.6,
            "isNew": false,
            "dietary": ["vegan"]
        },
        {
            "id": 23,
            "name": "Jackfruit Curry",
            "description": "Spiced jackfruit curry with coconut rice",
            "price": 20.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "hot",
            "prepTime": "30 mins",
            "rating": 4.8,
            "isNew": true,
            "dietary": ["vegan"]
        },
        {
            "id": 24,
            "name": "Mushroom Wellington",
            "description": "Portobello mushroom wrapped in puff pastry",
            "price": 22.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "45 mins",
            "rating": 4.7,
            "isNew": false,
            "dietary": ["vegan"]
        },
        {
            "id": 25,
            "name": "Lentil Shepherd's Pie",
            "description": "Seasoned lentils topped with mashed potatoes",
            "price": 19.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "40 mins",
            "rating": 4.6,
            "isNew": true,
            "dietary": ["vegan"]
        },
        {
            "id": 26,
            "name": "Chickpea Tagine",
            "description": "Moroccan-spiced chickpeas with couscous",
            "price": 18.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "35 mins",
            "rating": 4.5,
            "isNew": false,
            "dietary": ["vegan"]
        },
        {
            "id": 27,
            "name": "Pad Thai",
            "description": "Rice noodles with tofu and vegetables",
            "price": 17.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "25 mins",
            "rating": 4.7,
            "isNew": true,
            "dietary": ["vegan"]
        },
        {
            "id": 28,
            "name": "Stuffed Acorn Squash",
            "description": "Roasted squash with quinoa and vegetable stuffing",
            "price": 21.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "40 mins",
            "rating": 4.6,
            "isNew": false,
            "dietary": ["vegan"]
        },
        {
            "id": 29,
            "name": "Black Bean Burger",
            "description": "Homemade patty with avocado and vegan mayo",
            "price": 16.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "20 mins",
            "rating": 4.5,
            "isNew": true,
            "dietary": ["vegan"]
        },
        {
            "id": 30,
            "name": "Eggplant Lasagna",
            "description": "Layered eggplant with cashew cheese and marinara",
            "price": 20.99,
            "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "45 mins",
            "rating": 4.7,
            "isNew": false,
            "dietary": ["vegan"]
        },

        // Dairy-Free Options
        {
            "id": 31,
            "name": "Teriyaki Chicken",
            "description": "Grilled chicken with teriyaki sauce and steamed rice",
            "price": 23.99,
            "image": "https://images.unsplash.com/photo-1532550907401-a500c9a57435",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "25 mins",
            "rating": 4.7,
            "isNew": true,
            "dietary": ["dairy-free"]
        },
        {
            "id": 32,
            "name": "Grilled Shrimp Skewers",
            "description": "Lemon-herb marinated shrimp with quinoa",
            "price": 25.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "20 mins",
            "rating": 4.8,
            "isNew": false,
            "dietary": ["dairy-free"]
        },
        {
            "id": 33,
            "name": "Asian Stir-Fry Beef",
            "description": "Tender beef strips with vegetables in ginger sauce",
            "price": 24.99,
            "image": "https://images.unsplash.com/photo-1544025162-d76694265947",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "25 mins",
            "rating": 4.6,
            "isNew": true,
            "dietary": ["dairy-free"]
        },
        {
            "id": 34,
            "name": "Grilled Tuna Niçoise",
            "description": "Seared tuna with traditional Niçoise salad",
            "price": 26.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "30 mins",
            "rating": 4.7,
            "isNew": false,
            "dietary": ["dairy-free"]
        },
        {
            "id": 35,
            "name": "Duck Confit",
            "description": "Slow-cooked duck leg with roasted vegetables",
            "price": 32.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "40 mins",
            "rating": 4.9,
            "isNew": true,
            "dietary": ["dairy-free"]
        },
        {
            "id": 36,
            "name": "Grilled Pork Belly",
            "description": "Crispy pork belly with Asian slaw",
            "price": 27.99,
            "image": "https://images.unsplash.com/photo-1544025162-d76694265947",
            "category": "main-courses",
            "spicyLevel": "medium",
            "prepTime": "35 mins",
            "rating": 4.8,
            "isNew": false,
            "dietary": ["dairy-free"]
        },
        {
            "id": 37,
            "name": "Mediterranean Fish",
            "description": "Pan-seared fish with olive tapenade",
            "price": 28.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "25 mins",
            "rating": 4.7,
            "isNew": true,
            "dietary": ["dairy-free"]
        },
        {
            "id": 38,
            "name": "Korean BBQ Ribs",
            "description": "Marinated beef ribs with kimchi",
            "price": 29.99,
            "image": "https://images.unsplash.com/photo-1544025162-d76694265947",
            "category": "main-courses",
            "spicyLevel": "hot",
            "prepTime": "40 mins",
            "rating": 4.8,
            "isNew": false,
            "dietary": ["dairy-free"]
        },
        {
            "id": 39,
            "name": "Roasted Duck Breast",
            "description": "Pan-seared duck with cherry sauce",
            "price": 31.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "30 mins",
            "rating": 4.9,
            "isNew": true,
            "dietary": ["dairy-free"]
        },
        {
            "id": 40,
            "name": "Grilled Octopus",
            "description": "Tender octopus with Mediterranean herbs",
            "price": 30.99,
            "image": "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
            "category": "main-courses",
            "spicyLevel": "mild",
            "prepTime": "35 mins",
            "rating": 4.7,
            "isNew": false,
            "dietary": ["dairy-free"]
        }
    ],
    "appetizers": [
        {
            "id": 1,
            "name": "Bruschetta",
            "description": "Toasted bread with fresh tomatoes, basil, and extra virgin olive oil",
            "price": 12.99,
            "image": "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f",
            "category": "appetizers",
            "spicyLevel": "none",
            "prepTime": "15 mins",
            "rating": 4.5,
            "isNew": false,
            "dietary": ["vegetarian"]
        },
        {
            "id": 2,
            "name": "Tuna Tartare",
            "description": "Fresh sushi-grade tuna with avocado, sesame oil, and wonton crisps",
            "price": 16.99,
            "image": "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab",
            "category": "appetizers",
            "spicyLevel": "mild",
            "prepTime": "20 mins",
            "rating": 4.8,
            "isNew": true,
            "dietary": ["dairy-free", "gluten-free"]
        },
        {
            "id": 3,
            "name": "Crispy Buffalo Cauliflower",
            "description": "Battered cauliflower florets tossed in buffalo sauce with vegan ranch",
            "price": 13.99,
            "image": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
            "category": "appetizers",
            "spicyLevel": "medium",
            "prepTime": "25 mins",
            "rating": 4.6,
            "isNew": true,
            "dietary": ["vegan", "dairy-free"]
        }
    ],
    'desserts': [
        {
            id: 4,
            name: 'Crème Brûlée',
            description: 'Classic French dessert with caramelized sugar top',
            price: 9.99,
            image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc',
            category: 'desserts',
            prepTime: '20 mins',
            rating: 4.7,
            isNew: false,
            dietary: ['vegetarian']
        },
        {
            id: 5,
            name: 'Chocolate Lava Cake',
            description: 'Warm chocolate cake with molten center',
            price: 11.99,
            image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c',
            category: 'desserts',
            prepTime: '18 mins',
            rating: 4.9,
            isNew: true,
            dietary: ['vegetarian']
        },
    ],
    'drinks': [
        {
            id: 6,
            name: 'Signature Mojito',
            description: 'Fresh mint, lime, and premium rum',
            price: 12.99,
            image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a',
            category: 'drinks',
            prepTime: '5 mins',
            rating: 4.6,
            isNew: false,
            dietary: ['vegan']
        },
    ],
};
